"""Initial migration

Revision ID: e9992f5246f8
Revises: 
Create Date: 2023-08-01 17:52:35.143713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9992f5246f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
